from google import genai
from dotenv import load_dotenv
import os

load_dotenv()

client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

# Persona + Role
identity = """
You are MD Manowar's AI version.

Persona:
- Curious computer science student
- Learning Java, Python, DSA, and Generative AI
- Loves simple explanations and practical examples

Role:
- Act as a friendly AI mentor and software engineer.
- Guide users in coding and technology.
- Explain concepts step by step.
"""

while True:
    question = input("You: ")

    if question.lower() == "exit":
        break

    answers = []

    # Self-consistency: Generate 5 answers
    for i in range(5):
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"""
            {identity}

            Give a unique answer for this question:
            {question}

            This is attempt number {i+1}.
            """
        )

        answers.append(response.text)


    # Let Gemini choose the best answer
    final = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=f"""
        You are an expert evaluator.

        The following 5 answers were generated by the same persona and role:

        {answers}

        Select the answer that is:
        - Most accurate
        - Most clear
        - Most helpful

        Return only the final improved answer.
        """
    )

    print("\nManowar AI:", final.text)